// AUTO-GENERATED from the system IANA tz database (/usr/share/zoneinfo/zone.tab +
// iso3166.tab + tzdata.zi). Do not edit by hand — regenerate from those files.
//   TZ_COUNTRY: canonical zone -> primary country name (labels the picker).
//   TZ_ALIAS:   legacy alias zone -> canonical zone (e.g. Asia/Saigon -> Asia/Ho_Chi_Minh),
//               so a system clock set to an alias resolves to the canonical option.
const TZ_COUNTRY = {
  "Asia/Kabul": "Afghanistan",
  "Europe/Mariehamn": "Åland Islands",
  "Europe/Tirane": "Albania",
  "Africa/Algiers": "Algeria",
  "Europe/Andorra": "Andorra",
  "Africa/Luanda": "Angola",
  "America/Anguilla": "Anguilla",
  "Antarctica/Casey": "Antarctica",
  "Antarctica/Davis": "Antarctica",
  "Antarctica/DumontDUrville": "Antarctica",
  "Antarctica/Mawson": "Antarctica",
  "Antarctica/McMurdo": "Antarctica",
  "Antarctica/Palmer": "Antarctica",
  "Antarctica/Rothera": "Antarctica",
  "Antarctica/Syowa": "Antarctica",
  "Antarctica/Troll": "Antarctica",
  "Antarctica/Vostok": "Antarctica",
  "America/Antigua": "Antigua & Barbuda",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Argentina/Catamarca": "Argentina",
  "America/Argentina/Cordoba": "Argentina",
  "America/Argentina/Jujuy": "Argentina",
  "America/Argentina/La_Rioja": "Argentina",
  "America/Argentina/Mendoza": "Argentina",
  "America/Argentina/Rio_Gallegos": "Argentina",
  "America/Argentina/Salta": "Argentina",
  "America/Argentina/San_Juan": "Argentina",
  "America/Argentina/San_Luis": "Argentina",
  "America/Argentina/Tucuman": "Argentina",
  "America/Argentina/Ushuaia": "Argentina",
  "Asia/Yerevan": "Armenia",
  "America/Aruba": "Aruba",
  "Antarctica/Macquarie": "Australia",
  "Australia/Adelaide": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Broken_Hill": "Australia",
  "Australia/Darwin": "Australia",
  "Australia/Eucla": "Australia",
  "Australia/Hobart": "Australia",
  "Australia/Lindeman": "Australia",
  "Australia/Lord_Howe": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Sydney": "Australia",
  "Europe/Vienna": "Austria",
  "Asia/Baku": "Azerbaijan",
  "America/Nassau": "Bahamas",
  "Asia/Bahrain": "Bahrain",
  "Asia/Dhaka": "Bangladesh",
  "America/Barbados": "Barbados",
  "Europe/Minsk": "Belarus",
  "Europe/Brussels": "Belgium",
  "America/Belize": "Belize",
  "Africa/Porto-Novo": "Benin",
  "Atlantic/Bermuda": "Bermuda",
  "Asia/Thimphu": "Bhutan",
  "America/La_Paz": "Bolivia",
  "Europe/Sarajevo": "Bosnia & Herzegovina",
  "Africa/Gaborone": "Botswana",
  "America/Araguaina": "Brazil",
  "America/Bahia": "Brazil",
  "America/Belem": "Brazil",
  "America/Boa_Vista": "Brazil",
  "America/Campo_Grande": "Brazil",
  "America/Cuiaba": "Brazil",
  "America/Eirunepe": "Brazil",
  "America/Fortaleza": "Brazil",
  "America/Maceio": "Brazil",
  "America/Manaus": "Brazil",
  "America/Noronha": "Brazil",
  "America/Porto_Velho": "Brazil",
  "America/Recife": "Brazil",
  "America/Rio_Branco": "Brazil",
  "America/Santarem": "Brazil",
  "America/Sao_Paulo": "Brazil",
  "Europe/London": "Britain (UK)",
  "Indian/Chagos": "British Indian Ocean Territory",
  "Asia/Brunei": "Brunei",
  "Europe/Sofia": "Bulgaria",
  "Africa/Ouagadougou": "Burkina Faso",
  "Africa/Bujumbura": "Burundi",
  "Asia/Phnom_Penh": "Cambodia",
  "Africa/Douala": "Cameroon",
  "America/Atikokan": "Canada",
  "America/Blanc-Sablon": "Canada",
  "America/Cambridge_Bay": "Canada",
  "America/Creston": "Canada",
  "America/Dawson": "Canada",
  "America/Dawson_Creek": "Canada",
  "America/Edmonton": "Canada",
  "America/Fort_Nelson": "Canada",
  "America/Glace_Bay": "Canada",
  "America/Goose_Bay": "Canada",
  "America/Halifax": "Canada",
  "America/Inuvik": "Canada",
  "America/Iqaluit": "Canada",
  "America/Moncton": "Canada",
  "America/Rankin_Inlet": "Canada",
  "America/Regina": "Canada",
  "America/Resolute": "Canada",
  "America/St_Johns": "Canada",
  "America/Swift_Current": "Canada",
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Whitehorse": "Canada",
  "America/Winnipeg": "Canada",
  "Atlantic/Cape_Verde": "Cape Verde",
  "America/Kralendijk": "Caribbean NL",
  "America/Cayman": "Cayman Islands",
  "Africa/Bangui": "Central African Rep.",
  "Africa/Ndjamena": "Chad",
  "America/Coyhaique": "Chile",
  "America/Punta_Arenas": "Chile",
  "America/Santiago": "Chile",
  "Pacific/Easter": "Chile",
  "Asia/Shanghai": "China",
  "Asia/Urumqi": "China",
  "Indian/Christmas": "Christmas Island",
  "Indian/Cocos": "Cocos (Keeling) Islands",
  "America/Bogota": "Colombia",
  "Indian/Comoro": "Comoros",
  "Africa/Kinshasa": "Congo (Dem. Rep.)",
  "Africa/Lubumbashi": "Congo (Dem. Rep.)",
  "Africa/Brazzaville": "Congo (Rep.)",
  "Pacific/Rarotonga": "Cook Islands",
  "America/Costa_Rica": "Costa Rica",
  "Africa/Abidjan": "Côte d’Ivoire",
  "Europe/Zagreb": "Croatia",
  "America/Havana": "Cuba",
  "America/Curacao": "Curaçao",
  "Asia/Famagusta": "Cyprus",
  "Asia/Nicosia": "Cyprus",
  "Europe/Prague": "Czech Republic",
  "Europe/Copenhagen": "Denmark",
  "Africa/Djibouti": "Djibouti",
  "America/Dominica": "Dominica",
  "America/Santo_Domingo": "Dominican Republic",
  "Asia/Dili": "East Timor",
  "America/Guayaquil": "Ecuador",
  "Pacific/Galapagos": "Ecuador",
  "Africa/Cairo": "Egypt",
  "America/El_Salvador": "El Salvador",
  "Africa/Malabo": "Equatorial Guinea",
  "Africa/Asmara": "Eritrea",
  "Europe/Tallinn": "Estonia",
  "Africa/Mbabane": "Eswatini (Swaziland)",
  "Africa/Addis_Ababa": "Ethiopia",
  "Atlantic/Stanley": "Falkland Islands",
  "Atlantic/Faroe": "Faroe Islands",
  "Pacific/Fiji": "Fiji",
  "Europe/Helsinki": "Finland",
  "Europe/Paris": "France",
  "America/Cayenne": "French Guiana",
  "Pacific/Gambier": "French Polynesia",
  "Pacific/Marquesas": "French Polynesia",
  "Pacific/Tahiti": "French Polynesia",
  "Indian/Kerguelen": "French S. Terr.",
  "Africa/Libreville": "Gabon",
  "Africa/Banjul": "Gambia",
  "Asia/Tbilisi": "Georgia",
  "Europe/Berlin": "Germany",
  "Europe/Busingen": "Germany",
  "Africa/Accra": "Ghana",
  "Europe/Gibraltar": "Gibraltar",
  "Europe/Athens": "Greece",
  "America/Danmarkshavn": "Greenland",
  "America/Nuuk": "Greenland",
  "America/Scoresbysund": "Greenland",
  "America/Thule": "Greenland",
  "America/Grenada": "Grenada",
  "America/Guadeloupe": "Guadeloupe",
  "Pacific/Guam": "Guam",
  "America/Guatemala": "Guatemala",
  "Europe/Guernsey": "Guernsey",
  "Africa/Bissau": "Guinea-Bissau",
  "Africa/Conakry": "Guinea",
  "America/Guyana": "Guyana",
  "America/Port-au-Prince": "Haiti",
  "America/Tegucigalpa": "Honduras",
  "Asia/Hong_Kong": "Hong Kong",
  "Europe/Budapest": "Hungary",
  "Atlantic/Reykjavik": "Iceland",
  "Asia/Kolkata": "India",
  "Asia/Jakarta": "Indonesia",
  "Asia/Jayapura": "Indonesia",
  "Asia/Makassar": "Indonesia",
  "Asia/Pontianak": "Indonesia",
  "Asia/Tehran": "Iran",
  "Asia/Baghdad": "Iraq",
  "Europe/Dublin": "Ireland",
  "Europe/Isle_of_Man": "Isle of Man",
  "Asia/Jerusalem": "Israel",
  "Europe/Rome": "Italy",
  "America/Jamaica": "Jamaica",
  "Asia/Tokyo": "Japan",
  "Europe/Jersey": "Jersey",
  "Asia/Amman": "Jordan",
  "Asia/Almaty": "Kazakhstan",
  "Asia/Aqtau": "Kazakhstan",
  "Asia/Aqtobe": "Kazakhstan",
  "Asia/Atyrau": "Kazakhstan",
  "Asia/Oral": "Kazakhstan",
  "Asia/Qostanay": "Kazakhstan",
  "Asia/Qyzylorda": "Kazakhstan",
  "Africa/Nairobi": "Kenya",
  "Pacific/Kanton": "Kiribati",
  "Pacific/Kiritimati": "Kiribati",
  "Pacific/Tarawa": "Kiribati",
  "Asia/Pyongyang": "Korea (North)",
  "Asia/Seoul": "Korea (South)",
  "Asia/Kuwait": "Kuwait",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Vientiane": "Laos",
  "Europe/Riga": "Latvia",
  "Asia/Beirut": "Lebanon",
  "Africa/Maseru": "Lesotho",
  "Africa/Monrovia": "Liberia",
  "Africa/Tripoli": "Libya",
  "Europe/Vaduz": "Liechtenstein",
  "Europe/Vilnius": "Lithuania",
  "Europe/Luxembourg": "Luxembourg",
  "Asia/Macau": "Macau",
  "Indian/Antananarivo": "Madagascar",
  "Africa/Blantyre": "Malawi",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Kuching": "Malaysia",
  "Indian/Maldives": "Maldives",
  "Africa/Bamako": "Mali",
  "Europe/Malta": "Malta",
  "Pacific/Kwajalein": "Marshall Islands",
  "Pacific/Majuro": "Marshall Islands",
  "America/Martinique": "Martinique",
  "Africa/Nouakchott": "Mauritania",
  "Indian/Mauritius": "Mauritius",
  "Indian/Mayotte": "Mayotte",
  "America/Bahia_Banderas": "Mexico",
  "America/Cancun": "Mexico",
  "America/Chihuahua": "Mexico",
  "America/Ciudad_Juarez": "Mexico",
  "America/Hermosillo": "Mexico",
  "America/Matamoros": "Mexico",
  "America/Mazatlan": "Mexico",
  "America/Merida": "Mexico",
  "America/Mexico_City": "Mexico",
  "America/Monterrey": "Mexico",
  "America/Ojinaga": "Mexico",
  "America/Tijuana": "Mexico",
  "Pacific/Chuuk": "Micronesia",
  "Pacific/Kosrae": "Micronesia",
  "Pacific/Pohnpei": "Micronesia",
  "Europe/Chisinau": "Moldova",
  "Europe/Monaco": "Monaco",
  "Asia/Hovd": "Mongolia",
  "Asia/Ulaanbaatar": "Mongolia",
  "Europe/Podgorica": "Montenegro",
  "America/Montserrat": "Montserrat",
  "Africa/Casablanca": "Morocco",
  "Africa/Maputo": "Mozambique",
  "Asia/Yangon": "Myanmar (Burma)",
  "Africa/Windhoek": "Namibia",
  "Pacific/Nauru": "Nauru",
  "Asia/Kathmandu": "Nepal",
  "Europe/Amsterdam": "Netherlands",
  "Pacific/Noumea": "New Caledonia",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Chatham": "New Zealand",
  "America/Managua": "Nicaragua",
  "Africa/Niamey": "Niger",
  "Africa/Lagos": "Nigeria",
  "Pacific/Niue": "Niue",
  "Pacific/Norfolk": "Norfolk Island",
  "Europe/Skopje": "North Macedonia",
  "Pacific/Saipan": "Northern Mariana Islands",
  "Europe/Oslo": "Norway",
  "Asia/Muscat": "Oman",
  "Asia/Karachi": "Pakistan",
  "Pacific/Palau": "Palau",
  "Asia/Gaza": "Palestine",
  "Asia/Hebron": "Palestine",
  "America/Panama": "Panama",
  "Pacific/Bougainville": "Papua New Guinea",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "America/Asuncion": "Paraguay",
  "America/Lima": "Peru",
  "Asia/Manila": "Philippines",
  "Pacific/Pitcairn": "Pitcairn",
  "Europe/Warsaw": "Poland",
  "Atlantic/Azores": "Portugal",
  "Atlantic/Madeira": "Portugal",
  "Europe/Lisbon": "Portugal",
  "America/Puerto_Rico": "Puerto Rico",
  "Asia/Qatar": "Qatar",
  "Indian/Reunion": "Réunion",
  "Europe/Bucharest": "Romania",
  "Asia/Anadyr": "Russia",
  "Asia/Barnaul": "Russia",
  "Asia/Chita": "Russia",
  "Asia/Irkutsk": "Russia",
  "Asia/Kamchatka": "Russia",
  "Asia/Khandyga": "Russia",
  "Asia/Krasnoyarsk": "Russia",
  "Asia/Magadan": "Russia",
  "Asia/Novokuznetsk": "Russia",
  "Asia/Novosibirsk": "Russia",
  "Asia/Omsk": "Russia",
  "Asia/Sakhalin": "Russia",
  "Asia/Srednekolymsk": "Russia",
  "Asia/Tomsk": "Russia",
  "Asia/Ust-Nera": "Russia",
  "Asia/Vladivostok": "Russia",
  "Asia/Yakutsk": "Russia",
  "Asia/Yekaterinburg": "Russia",
  "Europe/Astrakhan": "Russia",
  "Europe/Kaliningrad": "Russia",
  "Europe/Kirov": "Russia",
  "Europe/Moscow": "Russia",
  "Europe/Samara": "Russia",
  "Europe/Saratov": "Russia",
  "Europe/Ulyanovsk": "Russia",
  "Europe/Volgograd": "Russia",
  "Africa/Kigali": "Rwanda",
  "Pacific/Pago_Pago": "Samoa (American)",
  "Pacific/Apia": "Samoa (western)",
  "Europe/San_Marino": "San Marino",
  "Africa/Sao_Tome": "Sao Tome & Principe",
  "Asia/Riyadh": "Saudi Arabia",
  "Africa/Dakar": "Senegal",
  "Europe/Belgrade": "Serbia",
  "Indian/Mahe": "Seychelles",
  "Africa/Freetown": "Sierra Leone",
  "Asia/Singapore": "Singapore",
  "Europe/Bratislava": "Slovakia",
  "Europe/Ljubljana": "Slovenia",
  "Pacific/Guadalcanal": "Solomon Islands",
  "Africa/Mogadishu": "Somalia",
  "Africa/Johannesburg": "South Africa",
  "Atlantic/South_Georgia": "South Georgia & the South Sandwich Islands",
  "Africa/Juba": "South Sudan",
  "Africa/Ceuta": "Spain",
  "Atlantic/Canary": "Spain",
  "Europe/Madrid": "Spain",
  "Asia/Colombo": "Sri Lanka",
  "America/St_Barthelemy": "St Barthelemy",
  "Atlantic/St_Helena": "St Helena",
  "America/St_Kitts": "St Kitts & Nevis",
  "America/St_Lucia": "St Lucia",
  "America/Lower_Princes": "St Maarten (Dutch)",
  "America/Marigot": "St Martin (French)",
  "America/Miquelon": "St Pierre & Miquelon",
  "America/St_Vincent": "St Vincent",
  "Africa/Khartoum": "Sudan",
  "America/Paramaribo": "Suriname",
  "Arctic/Longyearbyen": "Svalbard & Jan Mayen",
  "Europe/Stockholm": "Sweden",
  "Europe/Zurich": "Switzerland",
  "Asia/Damascus": "Syria",
  "Asia/Taipei": "Taiwan",
  "Asia/Dushanbe": "Tajikistan",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Asia/Bangkok": "Thailand",
  "Africa/Lome": "Togo",
  "Pacific/Fakaofo": "Tokelau",
  "Pacific/Tongatapu": "Tonga",
  "America/Port_of_Spain": "Trinidad & Tobago",
  "Africa/Tunis": "Tunisia",
  "Europe/Istanbul": "Turkey",
  "Asia/Ashgabat": "Turkmenistan",
  "America/Grand_Turk": "Turks & Caicos Is",
  "Pacific/Funafuti": "Tuvalu",
  "Africa/Kampala": "Uganda",
  "Europe/Kyiv": "Ukraine",
  "Europe/Simferopol": "Ukraine",
  "Asia/Dubai": "United Arab Emirates",
  "America/Adak": "United States",
  "America/Anchorage": "United States",
  "America/Boise": "United States",
  "America/Chicago": "United States",
  "America/Denver": "United States",
  "America/Detroit": "United States",
  "America/Indiana/Indianapolis": "United States",
  "America/Indiana/Knox": "United States",
  "America/Indiana/Marengo": "United States",
  "America/Indiana/Petersburg": "United States",
  "America/Indiana/Tell_City": "United States",
  "America/Indiana/Vevay": "United States",
  "America/Indiana/Vincennes": "United States",
  "America/Indiana/Winamac": "United States",
  "America/Juneau": "United States",
  "America/Kentucky/Louisville": "United States",
  "America/Kentucky/Monticello": "United States",
  "America/Los_Angeles": "United States",
  "America/Menominee": "United States",
  "America/Metlakatla": "United States",
  "America/New_York": "United States",
  "America/Nome": "United States",
  "America/North_Dakota/Beulah": "United States",
  "America/North_Dakota/Center": "United States",
  "America/North_Dakota/New_Salem": "United States",
  "America/Phoenix": "United States",
  "America/Sitka": "United States",
  "America/Yakutat": "United States",
  "Pacific/Honolulu": "United States",
  "America/Montevideo": "Uruguay",
  "Pacific/Midway": "US minor outlying islands",
  "Pacific/Wake": "US minor outlying islands",
  "Asia/Samarkand": "Uzbekistan",
  "Asia/Tashkent": "Uzbekistan",
  "Pacific/Efate": "Vanuatu",
  "Europe/Vatican": "Vatican City",
  "America/Caracas": "Venezuela",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "America/Tortola": "Virgin Islands (UK)",
  "America/St_Thomas": "Virgin Islands (US)",
  "Pacific/Wallis": "Wallis & Futuna",
  "Africa/El_Aaiun": "Western Sahara",
  "Asia/Aden": "Yemen",
  "Africa/Lusaka": "Zambia",
  "Africa/Harare": "Zimbabwe",
}

const TZ_ALIAS = {
  "Africa/Accra": "Africa/Abidjan",
  "Africa/Addis_Ababa": "Africa/Nairobi",
  "Africa/Asmara": "Africa/Nairobi",
  "Africa/Asmera": "Africa/Nairobi",
  "Africa/Bamako": "Africa/Abidjan",
  "Africa/Bangui": "Africa/Lagos",
  "Africa/Banjul": "Africa/Abidjan",
  "Africa/Blantyre": "Africa/Maputo",
  "Africa/Brazzaville": "Africa/Lagos",
  "Africa/Bujumbura": "Africa/Maputo",
  "Africa/Conakry": "Africa/Abidjan",
  "Africa/Dakar": "Africa/Abidjan",
  "Africa/Dar_es_Salaam": "Africa/Nairobi",
  "Africa/Djibouti": "Africa/Nairobi",
  "Africa/Douala": "Africa/Lagos",
  "Africa/Freetown": "Africa/Abidjan",
  "Africa/Gaborone": "Africa/Maputo",
  "Africa/Harare": "Africa/Maputo",
  "Africa/Kampala": "Africa/Nairobi",
  "Africa/Kigali": "Africa/Maputo",
  "Africa/Kinshasa": "Africa/Lagos",
  "Africa/Libreville": "Africa/Lagos",
  "Africa/Lome": "Africa/Abidjan",
  "Africa/Luanda": "Africa/Lagos",
  "Africa/Lubumbashi": "Africa/Maputo",
  "Africa/Lusaka": "Africa/Maputo",
  "Africa/Malabo": "Africa/Lagos",
  "Africa/Maseru": "Africa/Johannesburg",
  "Africa/Mbabane": "Africa/Johannesburg",
  "Africa/Mogadishu": "Africa/Nairobi",
  "Africa/Niamey": "Africa/Lagos",
  "Africa/Nouakchott": "Africa/Abidjan",
  "Africa/Ouagadougou": "Africa/Abidjan",
  "Africa/Porto-Novo": "Africa/Lagos",
  "Africa/Timbuktu": "Africa/Abidjan",
  "America/Anguilla": "America/Puerto_Rico",
  "America/Antigua": "America/Puerto_Rico",
  "America/Argentina/ComodRivadavia": "America/Argentina/Catamarca",
  "America/Aruba": "America/Puerto_Rico",
  "America/Atikokan": "America/Panama",
  "America/Atka": "America/Adak",
  "America/Blanc-Sablon": "America/Puerto_Rico",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "America/Catamarca": "America/Argentina/Catamarca",
  "America/Cayman": "America/Panama",
  "America/Coral_Harbour": "America/Panama",
  "America/Cordoba": "America/Argentina/Cordoba",
  "America/Creston": "America/Phoenix",
  "America/Curacao": "America/Puerto_Rico",
  "America/Dominica": "America/Puerto_Rico",
  "America/Ensenada": "America/Tijuana",
  "America/Fort_Wayne": "America/Indiana/Indianapolis",
  "America/Godthab": "America/Nuuk",
  "America/Grenada": "America/Puerto_Rico",
  "America/Guadeloupe": "America/Puerto_Rico",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "America/Jujuy": "America/Argentina/Jujuy",
  "America/Knox_IN": "America/Indiana/Knox",
  "America/Kralendijk": "America/Puerto_Rico",
  "America/Louisville": "America/Kentucky/Louisville",
  "America/Lower_Princes": "America/Puerto_Rico",
  "America/Marigot": "America/Puerto_Rico",
  "America/Mendoza": "America/Argentina/Mendoza",
  "America/Montreal": "America/Toronto",
  "America/Montserrat": "America/Puerto_Rico",
  "America/Nassau": "America/Toronto",
  "America/Nipigon": "America/Toronto",
  "America/Pangnirtung": "America/Iqaluit",
  "America/Port_of_Spain": "America/Puerto_Rico",
  "America/Porto_Acre": "America/Rio_Branco",
  "America/Rainy_River": "America/Winnipeg",
  "America/Rosario": "America/Argentina/Cordoba",
  "America/Santa_Isabel": "America/Tijuana",
  "America/Shiprock": "America/Denver",
  "America/St_Barthelemy": "America/Puerto_Rico",
  "America/St_Kitts": "America/Puerto_Rico",
  "America/St_Lucia": "America/Puerto_Rico",
  "America/St_Thomas": "America/Puerto_Rico",
  "America/St_Vincent": "America/Puerto_Rico",
  "America/Thunder_Bay": "America/Toronto",
  "America/Tortola": "America/Puerto_Rico",
  "America/Virgin": "America/Puerto_Rico",
  "America/Yellowknife": "America/Edmonton",
  "Antarctica/DumontDUrville": "Pacific/Port_Moresby",
  "Antarctica/McMurdo": "Pacific/Auckland",
  "Antarctica/South_Pole": "Pacific/Auckland",
  "Antarctica/Syowa": "Asia/Riyadh",
  "Arctic/Longyearbyen": "Europe/Berlin",
  "Asia/Aden": "Asia/Riyadh",
  "Asia/Ashkhabad": "Asia/Ashgabat",
  "Asia/Bahrain": "Asia/Qatar",
  "Asia/Brunei": "Asia/Kuching",
  "Asia/Calcutta": "Asia/Kolkata",
  "Asia/Choibalsan": "Asia/Ulaanbaatar",
  "Asia/Chongqing": "Asia/Shanghai",
  "Asia/Chungking": "Asia/Shanghai",
  "Asia/Dacca": "Asia/Dhaka",
  "Asia/Harbin": "Asia/Shanghai",
  "Asia/Istanbul": "Europe/Istanbul",
  "Asia/Kashgar": "Asia/Urumqi",
  "Asia/Katmandu": "Asia/Kathmandu",
  "Asia/Kuala_Lumpur": "Asia/Singapore",
  "Asia/Kuwait": "Asia/Riyadh",
  "Asia/Macao": "Asia/Macau",
  "Asia/Muscat": "Asia/Dubai",
  "Asia/Phnom_Penh": "Asia/Bangkok",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Saigon": "Asia/Ho_Chi_Minh",
  "Asia/Tel_Aviv": "Asia/Jerusalem",
  "Asia/Thimbu": "Asia/Thimphu",
  "Asia/Ujung_Pandang": "Asia/Makassar",
  "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
  "Asia/Vientiane": "Asia/Bangkok",
  "Atlantic/Faeroe": "Atlantic/Faroe",
  "Atlantic/Jan_Mayen": "Europe/Berlin",
  "Atlantic/Reykjavik": "Africa/Abidjan",
  "Atlantic/St_Helena": "Africa/Abidjan",
  "Australia/ACT": "Australia/Sydney",
  "Australia/Canberra": "Australia/Sydney",
  "Australia/Currie": "Australia/Hobart",
  "Australia/LHI": "Australia/Lord_Howe",
  "Australia/NSW": "Australia/Sydney",
  "Australia/North": "Australia/Darwin",
  "Australia/Queensland": "Australia/Brisbane",
  "Australia/South": "Australia/Adelaide",
  "Australia/Tasmania": "Australia/Hobart",
  "Australia/Victoria": "Australia/Melbourne",
  "Australia/West": "Australia/Perth",
  "Australia/Yancowinna": "Australia/Broken_Hill",
  "Brazil/Acre": "America/Rio_Branco",
  "Brazil/DeNoronha": "America/Noronha",
  "Brazil/East": "America/Sao_Paulo",
  "Brazil/West": "America/Manaus",
  "CET": "Europe/Brussels",
  "CST6CDT": "America/Chicago",
  "Canada/Atlantic": "America/Halifax",
  "Canada/Central": "America/Winnipeg",
  "Canada/Eastern": "America/Toronto",
  "Canada/Mountain": "America/Edmonton",
  "Canada/Newfoundland": "America/St_Johns",
  "Canada/Pacific": "America/Vancouver",
  "Canada/Saskatchewan": "America/Regina",
  "Canada/Yukon": "America/Whitehorse",
  "Chile/Continental": "America/Santiago",
  "Chile/EasterIsland": "Pacific/Easter",
  "Cuba": "America/Havana",
  "EET": "Europe/Athens",
  "EST": "America/Panama",
  "EST5EDT": "America/New_York",
  "Egypt": "Africa/Cairo",
  "Eire": "Europe/Dublin",
  "Etc/GMT+0": "Etc/GMT",
  "Etc/GMT-0": "Etc/GMT",
  "Etc/GMT0": "Etc/GMT",
  "Etc/Greenwich": "Etc/GMT",
  "Etc/UCT": "Etc/UTC",
  "Etc/Universal": "Etc/UTC",
  "Etc/Zulu": "Etc/UTC",
  "Europe/Amsterdam": "Europe/Brussels",
  "Europe/Belfast": "Europe/London",
  "Europe/Bratislava": "Europe/Prague",
  "Europe/Busingen": "Europe/Zurich",
  "Europe/Copenhagen": "Europe/Berlin",
  "Europe/Guernsey": "Europe/London",
  "Europe/Isle_of_Man": "Europe/London",
  "Europe/Jersey": "Europe/London",
  "Europe/Kiev": "Europe/Kyiv",
  "Europe/Ljubljana": "Europe/Belgrade",
  "Europe/Luxembourg": "Europe/Brussels",
  "Europe/Mariehamn": "Europe/Helsinki",
  "Europe/Monaco": "Europe/Paris",
  "Europe/Nicosia": "Asia/Nicosia",
  "Europe/Oslo": "Europe/Berlin",
  "Europe/Podgorica": "Europe/Belgrade",
  "Europe/San_Marino": "Europe/Rome",
  "Europe/Sarajevo": "Europe/Belgrade",
  "Europe/Skopje": "Europe/Belgrade",
  "Europe/Stockholm": "Europe/Berlin",
  "Europe/Tiraspol": "Europe/Chisinau",
  "Europe/Uzhgorod": "Europe/Kyiv",
  "Europe/Vaduz": "Europe/Zurich",
  "Europe/Vatican": "Europe/Rome",
  "Europe/Zagreb": "Europe/Belgrade",
  "Europe/Zaporozhye": "Europe/Kyiv",
  "GB": "Europe/London",
  "GB-Eire": "Europe/London",
  "GMT": "Etc/GMT",
  "GMT+0": "Etc/GMT",
  "GMT-0": "Etc/GMT",
  "GMT0": "Etc/GMT",
  "Greenwich": "Etc/GMT",
  "HST": "Pacific/Honolulu",
  "Hongkong": "Asia/Hong_Kong",
  "Iceland": "Africa/Abidjan",
  "Indian/Antananarivo": "Africa/Nairobi",
  "Indian/Christmas": "Asia/Bangkok",
  "Indian/Cocos": "Asia/Yangon",
  "Indian/Comoro": "Africa/Nairobi",
  "Indian/Kerguelen": "Indian/Maldives",
  "Indian/Mahe": "Asia/Dubai",
  "Indian/Mayotte": "Africa/Nairobi",
  "Indian/Reunion": "Asia/Dubai",
  "Iran": "Asia/Tehran",
  "Israel": "Asia/Jerusalem",
  "Jamaica": "America/Jamaica",
  "Japan": "Asia/Tokyo",
  "Kwajalein": "Pacific/Kwajalein",
  "Libya": "Africa/Tripoli",
  "MET": "Europe/Brussels",
  "MST": "America/Phoenix",
  "MST7MDT": "America/Denver",
  "Mexico/BajaNorte": "America/Tijuana",
  "Mexico/BajaSur": "America/Mazatlan",
  "Mexico/General": "America/Mexico_City",
  "NZ": "Pacific/Auckland",
  "NZ-CHAT": "Pacific/Chatham",
  "Navajo": "America/Denver",
  "PRC": "Asia/Shanghai",
  "PST8PDT": "America/Los_Angeles",
  "Pacific/Chuuk": "Pacific/Port_Moresby",
  "Pacific/Enderbury": "Pacific/Kanton",
  "Pacific/Funafuti": "Pacific/Tarawa",
  "Pacific/Johnston": "Pacific/Honolulu",
  "Pacific/Majuro": "Pacific/Tarawa",
  "Pacific/Midway": "Pacific/Pago_Pago",
  "Pacific/Pohnpei": "Pacific/Guadalcanal",
  "Pacific/Ponape": "Pacific/Guadalcanal",
  "Pacific/Saipan": "Pacific/Guam",
  "Pacific/Samoa": "Pacific/Pago_Pago",
  "Pacific/Truk": "Pacific/Port_Moresby",
  "Pacific/Wake": "Pacific/Tarawa",
  "Pacific/Wallis": "Pacific/Tarawa",
  "Pacific/Yap": "Pacific/Port_Moresby",
  "Poland": "Europe/Warsaw",
  "Portugal": "Europe/Lisbon",
  "ROC": "Asia/Taipei",
  "ROK": "Asia/Seoul",
  "Singapore": "Asia/Singapore",
  "Turkey": "Europe/Istanbul",
  "UCT": "Etc/UTC",
  "US/Alaska": "America/Anchorage",
  "US/Aleutian": "America/Adak",
  "US/Arizona": "America/Phoenix",
  "US/Central": "America/Chicago",
  "US/East-Indiana": "America/Indiana/Indianapolis",
  "US/Eastern": "America/New_York",
  "US/Hawaii": "Pacific/Honolulu",
  "US/Indiana-Starke": "America/Indiana/Knox",
  "US/Michigan": "America/Detroit",
  "US/Mountain": "America/Denver",
  "US/Pacific": "America/Los_Angeles",
  "US/Samoa": "Pacific/Pago_Pago",
  "UTC": "Etc/UTC",
  "Universal": "Etc/UTC",
  "W-SU": "Europe/Moscow",
  "WET": "Europe/Lisbon",
  "Zulu": "Etc/UTC",
}
